### ISSUE TITLE
Texas Alc. Bev. Code

### ISSUE THREAD

**Issue by convalia** [raindrum/citeurl#1]
When searching for an entry in the Texas Alcoholic Beverage Code (e.g. Tex. Alco. Bev. Code Ann. § 2.02(b)), the search returns a 404 at this address (https://statutes.capitol.texas.gov/Docs/AB/htm/AB.2.htm#2.02)

The correct address is (https://statutes.capitol.texas.gov/Docs/AL/htm/AL.2.htm#2.02)

**Comment by raindrum** [comment]
Thanks for pointing this out, and congrats on filing the first bug report! It should be fixed now.
